type WaterReading {
    location: Location
    temperature: Float
    time: String
}

type Location {
    id: Int
    lat: Float
    lng: Float
    name: String
    area: String
}

type AirReading {
    location: Location
    precip: Float
    temp: Float
    time: String
}

type Query {
    waterReadings(location: String): [WaterReading]
    airReadings(location: String): [AirReading]
    locations: [Location]
}

type Mutation {
    addWaterReading(reading: WaterReadingInput): WaterReading
}

input WaterReadingInput {
    location: Int
    temperature: Float
    time: String
}

input AirReadingInput {
    location: Int
    precip: Float
    temp: Float
    time: String
}